version: '3'
services:
    webapp:
        image: node:16
        working_dir: /home/node/app
        command: bash -c "npm install && npm run dev"
        volumes:
            - .:/home/node/app
        ports:
            - 5173:5173
            - 443:443
        networks:
            - threejsnode
        restart: on-failure
networks:
    threejsnode:
        driver: bridge